# Shell variables
# Generated by 'wal'
wallpaper='None'

# Special
background='#000000'
foreground='#ffffff'
cursor='#ff0000'

# Colors
color0='#000000'
color1='#ff0000'
color2='#ff0000'
color3='#ff0000'
color4='#ff0000'
color5='#ff0000'
color6='#ff0000'
color7='#ffffff'
color8='#000000'
color9='#ff0000'
color10='#ff0000'
color11='#ff0000'
color12='#ff0000'
color13='#ff0000'
color14='#ff0000'
color15='#ffffff'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
